#!/bin/bash

LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=successful&limit=40"

echo "LAST_SUCCESSFUL_BUILD_URL: " $LAST_SUCCESSFUL_BUILD_URL

LAST_SUCCESSFUL_COMMIT=`curl -Ss $LAST_SUCCESSFUL_BUILD_URL |jq -r ".[]|select(.build_parameters.CIRCLE_JOB == \"$CIRCLE_JOB\")|.[\"vcs_revision\"]" |head -n 1
echo "LAST_SUCCESSFUL_COMMIT: " $LAST_SUCCESSFUL_COMMIT


for arg in "$@"
do
  if [[ $(git diff $CIRCLE_SHA1..$LAST_SUCCESSFUL_COMMIT --name-status | grep "$arg") != "" ]]
  then
    exit 255
  fi
done
exit 0