addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.1")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"              % "2.0.0-M2")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "2.3")
// addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")